List<Map> globalPredict = [
  {'message': '[ПЬЯНЫЙ] [МУЖЧИНА]', 'sex': 'm'},
  {'message': '[ПЬЯНАЯ] [ЖЕНЩИНА]', 'sex': 'f'},
  {'message': '[ПЬЯНЫЕ] [ЛЮДИ]', 'sex': 'plural'},
  {'message': '[ДВЕ] [ПЬЯНЫЕ] [ЖЕНЩИНЫ]', 'sex': 'plural'},
  {'message': '[ПЬЯНЫЙ] [МУЖЧИНА] из [ГОРОДА]', 'sex': 'm'},
  {'message': '[ПЬЯНАЯ] [ЖЕНЩИНА] из [ГОРОДА]', 'sex': 'f'},
  {'message': '[ПЬЯНЫЕ] [ЛЮДИ] из [ГОРОДА]', 'sex': 'plural'},
  {'message': '[ДВЕ] [ПЬЯНЫЕ] [ЖЕНЩИНЫ] из [ГОРОДА]', 'sex': 'plural'},
  {'message': '[ПЬЯНЫЙ] [МУЖЧИНА] из [ГОРОДА], [РАСЧЛЕНИВШИЙ]', 'sex': 'm'},
  {'message': '[ШКОЛЬНИК]', 'sex': 'm'},
  {'message': '[ШКОЛЬНИЦА]', 'sex': 'f'},
  {'message': '[ДВЕ] [ШКОЛЬНИЦЫ]', 'sex': 'plural'},
  {'message': '[ШКОЛЬНИК] из [ГОРОДА]', 'sex': 'm'},
  {'message': '[ШКОЛЬНИЦА] из [ГОРОДА]', 'sex': 'f'},
  {'message': '[ДВЕ] [ШКОЛЬНИЦЫ] из [ГОРОДА]', 'sex': 'plural'},
  {'message': 'В [ГОРОДЕ] [ПЬЯНЫЙ] [МУЖЧИНА]', 'sex': 'm'},
  {'message': 'В [ГОРОДЕ] [ПЬЯНАЯ] [ЖЕНЩИНА]', 'sex': 'f'},
  {'message': 'В [ГОРОДЕ] [ПЬЯНЫЕ] [ЛЮДИ]', 'sex': 'plural'},
  {'message': 'В [ГОРОДЕ] [ДВЕ] [ПЬЯНЫЕ] [ЖЕНЩИНЫ]', 'sex': 'plural'},
  {'message': 'В [ГОРОДЕ] [ГРУППА_МУЖЧИН]', 'sex': 'plural'},
  {'message': 'В [ГОРОДЕ] [ШКОЛЬНИК]', 'sex': 'm'},
  {'message': 'В [ГОРОДЕ] [ШКОЛЬНИЦА]', 'sex': 'f'},
  {'message': 'В [ГОРОДЕ] [ДВЕ] [ШКОЛЬНИЦЫ]', 'sex': 'plural'},
  {'message': '[ПЬЯНЫЙ] [ЖИТЕЛЬ] [ГОРОДА]', 'sex': 'm'},
  {'message': '[ПЬЯНАЯ] [ЖИТЕЛЬНИЦА] [ГОРОДА]', 'sex': 'f'},
  {'message': '[ПЬЯНЫЕ] [ЖИТЕЛИ] [ГОРОДА]', 'sex': 'plural'},
  {'message': '[ПЬЯНЫЙ] [ОМИЧ]', 'sex': 'm'},
  {'message': '[ПЬЯНЫЙ] [ОМИЧ], [РАСЧЛЕНИВШИЙ]', 'sex': 'm'},
  {'message': '[ПЬЯНЫЙ] [ОМИЧ] [С_ПРЕДМЕТОМ]', 'sex': 'm'},
  {'message': '[МУЖЧИНА]', 'sex': 'm'},
  {'message': '[ЛЮДИ]', 'sex': 'plural'},
  {'message': '[ЖЕНЩИНА]', 'sex': 'f'},
  {'message': '[ЖЕНЩИНЫ]', 'sex': 'plural'},
  {'message': '[ШКОЛЬНИК]', 'sex': 'm'},
  {'message': '[ШКОЛЬНИЦА]', 'sex': 'f'},
  {'message': '[ОДНА_ПЛЮС_ОДНА]', 'sex': 'plural'},
  {'message': '[ДВА] студента [ВУЗА]', 'sex': 'plural'},
];

List<Map> globalPredictEn = [
  {'message': '[DRUNK] [MAN]', 'sex': 'm'},
  {'message': '[DRUNK] [WOMAN]', 'sex': 'f'},
  {'message': '[DRUNK] [PEOPLE]', 'sex': 'plural'},
  {'message': '[TWO] [DRUNK] [WOMEN]', 'sex': 'plural'},
  {'message': '[DRUNK] [MAN] from [CITY]', 'sex': 'm'},
  {'message': '[DRUNK] [WOMAN] from [CITY]', 'sex': 'f'},
  {'message': '[DRUNK] [PEOPLE] from [CITY]', 'sex': 'plural'},
  {'message': '[TWO] [DRUNK] [WOMEN] from [CITY]', 'sex': 'plural'},
  {'message': '[TEEN_BOY]', 'sex': 'm'},
  {'message': '[TEEN_GIRL]', 'sex': 'f'},
  {'message': '[TWO] [TEEN_GIRLS]', 'sex': 'plural'},
  {'message': '[TEEN_BOY] from [CITY]', 'sex': 'm'},
  {'message': '[TEEN_GIRL] from [CITY]', 'sex': 'f'},
  {'message': '[TWO] [TEEN_GIRLS] from [CITY]', 'sex': 'plural'},
  {'message': 'In [CITY] [DRUNK] [MAN]', 'sex': 'm'},
  {'message': 'In [CITY] [DRUNK] [WOMAN]', 'sex': 'f'},
  {'message': 'In [CITY] [DRUNK] [PEOPLE]', 'sex': 'plural'},
  {'message': 'In [CITY] [TWO] [DRUNK] [WOMEN]', 'sex': 'plural'},
  {'message': 'In [CITY] [GROUP_OF_MEN]', 'sex': 'plural'},
  {'message': 'In [CITY] [TEEN_BOY]', 'sex': 'm'},
  {'message': 'In [CITY] [TEEN_GIRL]', 'sex': 'f'},
  {'message': 'In [CITY] [TWO] [TEEN_GIRLS]', 'sex': 'plural'},
  {'message': '[DRUNK] [RESIDENT] of [CITY]', 'sex': 'm'},
  {'message': '[DRUNK] [RESIDENT_F] of [CITY]', 'sex': 'f'},
  {'message': '[DRUNK] [RESIDENTS] of [CITY]', 'sex': 'plural'},
  {'message': '[MAN]', 'sex': 'm'},
  {'message': '[PEOPLE]', 'sex': 'plural'},
  {'message': '[WOMAN]', 'sex': 'f'},
  {'message': '[WOMEN]', 'sex': 'plural'},
  {'message': '[TEEN_BOY]', 'sex': 'm'},
  {'message': '[TEEN_GIRL]', 'sex': 'f'},
  {'message': '[ONE_PLUS_ONE]', 'sex': 'plural'},
  {'message': '[TWO] students of [UNIVERSITY]', 'sex': 'plural'},
];

Map<String, List> globalSets = {
  'МУЖЧИНА': [
    'азиат',
    'болельщик из стоп-листа ФСБ',
    'дебошир',
    'домушник',
    'тунеядец',
    'пенсионер с простреленной ногой',
    'баскетболист местного клуба',
    'азиат',
    'бизнесмен',
    'ветеран ВОВ',
    'Водитель [КАМАЗА]',
    'вор-форточник',
    'грузчик',
    'дворник',
    'директор зоопарка',
    'извращенец',
    'инвалид',
    'лысый самоубийца',
    'меценат',
    'миллионер',
    'министр',
    'мормон',
    'мужчина',
    'наркоман',
    'нищий',
    'охотник',
    'парень',
    'пенсионер',
    'пивовар',
    'пиротехник-самоучка',
    'пожилой учитель',
    'полицейский',
    'Председатель колхоза',
    'лейтенант',
    'программист',
    'протоиерей',
    'рабочий',
    'разнорабочий',
    'азиат',
    'рыбак',
    'сантехник',
    'сатанист',
    'священник',
    'сотрудник росгвардии',
    'социальный работник',
    'судья',
    'телеведущий',
    'транссексуал',
    'футболист',
    'хозяин конопляной лаборатории',
    'чеченец',
    'экспедитор',
    'поджигатель сараев',
  ],
  'МУЖЧИНЫ': [
    'адвокаты',
    'алгоголики',
    'бывшые заключенные',
    'коммунальщики',
    'наркоманы',
    'оппозиционеры',
    'преступники',
    'участники преступной группировки',
  ],
  'ГРУППА_МУЖЧИН': [
    'группа молодых людей',
    'группа томичей',
    'двое чеченцев',
  ],
  'ШКОЛЬНИК': [
    'детдомовец',
    'малолетний вредитель',
    'мальчик',
    'молодой человек',
    'подросток',
    'парень',
    'третьеклассник',
    'четвероклассник',
    'школьник',
  ],
  'ЖЕНЩИНА': [
    'владелица мебельного цеха',
    'воспитательница',
    'двукратная олимпийская чемпионка',
    'жена',
    'женщина',
    'женщина лёгкого поведения',
    'журналистка',
    'известная биатлонистка',
    'мошенница',
    'пенсионерка',
    'писательница',
    'посетительница салона красоты',
    'пьяная продавщица',
    'сотрудница свердловской железной дороги',
    'старушка',
    'уборщица ночного клуба',
    'учительница',
    'учительница физкультуры',
  ],
  'ЖЕНЩИНЫ': [
    'девушки',
    'мошенницы-гипнотизерши',
    'пенсионерки',
    'писательницы',
    'проститутки',
    'пьяные продавщицы',
    'учительницы',
    'посетительницы салона красоты',
    'студентки',
    'старушки',
    'женщины лёгкого поведения',
  ],
  'ШКОЛЬНИЦА': [
    'воспитанница детского дома',
    'девочка',
    'девушка',
    'отличница',
    'студентка',
    'школьница',
  ],
  'ШКОЛЬНИЦЫ': [
    'воспитанницы детского дома',
    'девочки',
    'девушки',
    'отличницы',
    'студентки',
    'школьницы',
  ],
  'ОДНА_ПЛЮС_ОДНА': [
    'беременная женщина с напарницей',
  ],
  'ЖИТЕЛЬ': [
    'глава администрации',
    'Депутат',
    'житель',
    'мэр',
    'почётный гражданин',
    'экс-мэр',
    'экс-прокурор',
  ],
  'ЖИТЕЛЬНИЦА': [
    'жительница',
    'уроженка',
  ],
  'ЖИТЕЛИ': [
    'жители',
    'двое жителей',
    'уроженцы',
  ],
  'МУЖА': ['мужа', 'свекровь', 'сестру'],
  'ОМИЧ': [
    'Донской казак',
    'Казах',
    'Кемеровчанин',
    'Китаец',
    'Нанаец',
    'Немец',
    'Омич',
    'Череповчанин',
    'Харьковчанин',
    'Ярославец',
  ],
  'ОМИЧИ': [
    'Омичи',
  ],
  'ПЕНСИОНЕРОВ': [
    'азиатов',
    'домушников',
    'тунеядцев',
    'баскетболистов местного клуба',
    'бизнесменов',
    'ветеранов ВОВ',
    'водителей',
    'грузчиков',
    'дворников',
    'детдомовцев',
    'жителей коттеджного посёлка',
    'молодых людей',
    'мормонов',
    'мужчин',
    'наркоманов',
    'нищих',
    'охотников',
    'пенсионеров',
    'подростков',
    'пожилых учителей',
    'полицейских',
    'свидетелей иеговы',
    'прихожан местной церкви',
    'программистов',
    'рабочих',
    'рыбаков',
    'сантехников',
    'сатанистов',
    'священников',
    'социальных работников',
    'футболистов',
    'чеченцев',
    'школьников',
  ],
  'ЛЮДИ': [
    'активисты Навального',
    'зоозащитники',
    'пожарные',
    'неизвестные',
    'полицейские',
    'посетители кафе',
    'украинские рыбаки',
    'фанаты макса коржа',
    'хакеры',
  ],
  'СОСЕДА': [
    '',
    'гуся',
    'двух павлинов',
    'двух прохожих',
    'двух студенток',
    'депутата',
    'козу',
    'корову',
    'кошку',
    'несколько зевак',
    'полицейского',
    'прохожего',
    'собаку',
    'соседа',
  ],
  'С_ПРЕДМЕТОМ': [
    'с лазерной указкой',
    'с топором',
  ],
  'ПУТИНЫМ': [
    'медведевым',
    'президентом',
    'губернатором',
    'путиным',
    'премьер-министром Канады'
  ],
  'ЖЕНУ': ['ТЁЩУ', 'ЖЕНУ'],
  'КАМАЗА': [
    'автобуса',
    'белаза',
    'буксира',
    'камаза',
    'катка',
    'маршрутки',
    'мусоровоза',
    'скорой помощи',
    'трамвая',
  ],
  'МАРШРУТКУ': [
    'бетономешалку',
    'катафалк',
    'патрульный катер',
    'ПОЕЗД',
    'танк-экспонат времен ВОВ',
    'трамвай',
    'трактор',
    'троллейбус',
  ],
  'ГОРОДА': [
    'Амурской области',
    'Бобруйска',
    'Бурятии',
    'Владимирской области',
    'Воронежа',
    'Донецка',
    'Иваново',
    'Кавказа',
    'Калининграда',
    'Китая',
    'Колонии-поселения',
    'Костромы',
    'Кузбасса',
    'Крыма',
    'Мурманска',
    'Подмосковья',
    'Прибалтики',
    'Приморья',
    'Санкт-Петербурга',
    'Саратова',
    'Сочи',
    'Ставрополья',
    'Ульяновска',
    'Узбекистана',
    'Хабаровска',
    'Якутии',
    'Ярославской области',
    'анадыря',
    'большого камня',
    'владивостока',
    'калужской области',
    'коттеджного посёлка',
    'крыма',
    'новороссийска',
    'провинциального городка',
    'тюмени',
    'челябинска',
    'якутска',
  ],
  'САРАТОВСКИЙ': [
    'бобруйский',
    'кемеровский',
    'саратовский',
    'тверской',
  ],
  'САРАТОВСКАЯ': [
    'хабаровская',
    'иркутская',
    'московская',
    'краснодарская',
  ],
  'САРАТОВСКИЕ': [
    'новосибирские',
    'владивостокские',
    'сахалинские',
    'ростовские',
    'минские',
    'киевские',
  ],
  'ГОРОДЕ': [
    'Амурске',
    'Баку',
    'Воронеже',
    'Грозном',
    'Дальнегорске',
    'Екатеринбурге',
    'Краснодаре',
    'Казани',
    'Киргизстане',
    'Луганске',
    'Магадане',
    'Новосибирске',
    'Оренбурге',
    'Петербурге',
    'Реутове',
    'Самаре',
    'Ташкенте',
    'Узбекистане',
    'Челябинске',
    'Чите',
  ],
  'СОБАКУ': [
    'СОБАКУ',
    'ЯЩИК ВОДКИ',
    'ламу',
    'льва из местного цирка',
    'деньги дольщиков',
    'теленка',
    'более сотни коров'
  ],
  'СВОЕГО_ЛЮБИМЦА': [
    'СОБАКУ',
    'ЯЩИК ВОДКИ',
    'любимого котёнка',
    'домашнего фазана',
    'деньги дольщиков',
    'теленка',
    'инвалида'
  ],
  'ПЬЯНЫЙ': ['пьяный', 'пожилой'],
  'ПЬЯНАЯ': ['пьяная', 'пожилая'],
  'ПЬЯНЫЕ': ['пьяные', 'пожилые'],
  'НАДРУГАЛАСЬ': ['надругалась'],
  'ЛИШИЛСЯ': [
    'автомобиля',
    'волос',
    'денег',
    'документов',
    'жилища',
    'ноги',
    'пальца',
    'полового органа',
    'руки',
  ],
  'УБИЛИ': [
    'задушили',
    'зарезали',
    'застрелили',
    'казнили',
    'осквернили',
    'подожгли',
    'ранили',
    'убили',
    'унизили',
    'утопили'
  ],
  'УБИЛА': [
    'убила',
    'ранила',
    'казнила',
    'унизила',
    'осквернила',
    'застрелила',
    'задушила',
    'утопила',
    'зарезала'
  ],
  'УБИЛ': [
    'убил ',
    'ранил ',
    'казнил ',
    'унизил ',
    'осквернил ',
    'застрелил ',
    'задушил',
    ' утопил ',
    'зарезал'
  ],
  'ВЗОРВАЛ': ['взорвал', 'поджёг', 'расстрелял'],
  'ВЗОРВАЛА': ['взорвала', 'подожгла', 'расстреляла'],
  'ВЗОРВАЛИ': ['взорвали', 'подожгли', 'расстреляли'],
  'УБИТЬ': ['НАПУГАТЬ', 'УБИТЬ'],
  'ВЕРНУТЬ_М': ['супругу', 'сожительницу', 'жену', 'девушку', 'честь семьи'],
  'ВЕРНУТЬ_Ж': [
    'супруга',
    'сожителя',
    'мужа',
    'ребёнка-наркомана из клиники',
    'честь семьи'
  ],
  'СЛУЧАЙНО': ['случайно', '', '', '', ''],
  'ДВА': ['Два', 'Три'],
  'ДВЕ': ['Две', 'Три'],
  'БУДКУ': [
    'свой гараж',
    'гаражный кооператив',
    'самогонный аппарат',
    'рекламный щит',
    'трансформаторную будку',
    'беседку с молодежью'
  ],
  'ВУЗА': ['филфака МГУ', 'Гнесинки'],
  'РАСЧЛЕНИВШИЙ': [
    'зверски расчленивший соседа',
    'зверски расчленивший лягушку',
    'избивший инвалида',
    'сломавший мужчине ключицу',
    'стрелявший в прохожих из окна',
  ],
};

Map<String, List> globalSetsEn = {
  'GARAGE': [
    'a garage',
    'a garden shed',
    'a billboard',
    'a food truck',
    'a propane tank',
    'a backyard gazebo',
  ],
  'UNIVERSITY': ['MIT', 'Harvard', 'Stanford', 'UCLA', 'Ohio State', 'community college'],
  'MAN': [
    'plumber',
    'millionaire',
    'zoo director',
    'janitor',
    'retired teacher',
    'programmer',
    'fisherman',
    'priest',
    'electrician',
    'mall Santa',
    'Uber driver',
    'HOA president',
    'food truck owner',
    'beekeeper',
    'lighthouse keeper',
    'man',
    'retiree',
    'police officer',
    'firefighter',
    'lumberjack',
    'brewer',
    'tax accountant',
    'golf instructor',
    'podcast host',
  ],
  'WOMAN': [
    'daycare teacher',
    'writer',
    'retiree',
    'woman',
    'journalist',
    'biathlon coach',
    'beauty salon regular',
    'school principal',
    'bakery owner',
    'yoga instructor',
    'city council member',
    'veterinarian',
    'night shift nurse',
    'librarian',
  ],
  'WOMEN': [
    'women',
    'retirees',
    'writers',
    'teachers',
    'students',
    'book club members',
    'HOA board members',
  ],
  'TEEN_BOY': [
    'boy',
    'teenager',
    'high school student',
    'paper route kid',
    'skateboarder',
    'eighth grader',
  ],
  'TEEN_GIRL': [
    'girl',
    'teenager',
    'honor student',
    'high school student',
    'cheerleader',
    'babysitter',
  ],
  'TEEN_GIRLS': [
    'girls',
    'teenagers',
    'honor students',
    'high school students',
  ],
  'GROUP_OF_MEN': [
    'a group of young men',
    'a group of local guys',
    'two cousins',
    'three roommates',
  ],
  'PEOPLE': [
    'firefighters',
    'bird watchers',
    'podcasters',
    'zoo volunteers',
    'neighbors',
    'karaoke fans',
    'coupon collectors',
    'mystery shoppers',
  ],
  'ONE_PLUS_ONE': [
    'pregnant woman with her friend',
    'two influencers',
    'two dog walkers',
  ],
  'RESIDENT': [
    'mayor',
    'local man',
    'retiree',
    'deputy',
    'honorary citizen',
    'ex-mayor',
  ],
  'RESIDENT_F': [
    'local woman',
    'lifelong resident',
    'retiree',
  ],
  'RESIDENTS': [
    'locals',
    'two residents',
    'lifelong residents',
  ],
  'WIFE': ['his wife', 'his mother-in-law', 'his sister'],
  'TRAIN': [
    'a bus',
    'a tractor',
    'a concrete mixer',
    'a WW2 tank on display',
    'a tram',
    'a trolleybus',
    'a patrol boat',
    'a school bus',
  ],
  'HUSBAND': ['her husband', 'her ex-boyfriend', 'her brother-in-law'],
  'CITY': [
    'Ohio',
    'Florida',
    'Texas',
    'Chicago',
    'Portland',
    'Detroit',
    'rural Maine',
    'suburban Denver',
    'Las Vegas',
    'Seattle',
    'Boston',
    'Nashville',
    'Phoenix',
    'Atlanta',
    'Philadelphia',
    'San Diego',
    'a small college town',
    'a gated community',
  ],
  'PET': ['a dog', 'a cat', 'a parrot', 'a hamster', 'a turtle', 'a goat'],
  'NEIGHBOR': [
    'neighbor',
    'passerby',
    'two passersby',
    'two college students',
    'the mail carrier',
    'dog',
    'goat',
    'cat',
    'goose',
    'two peacocks',
  ],
  'DRUNK': ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'drunk'],
  'KILLED': [
    'startled',
    'confused',
    'sued',
    'blocked on Facebook',
    'reported to the HOA',
    'filmed for TikTok',
    'called the police on',
    'mistaken for a burglar',
    'chased off the lawn',
  ],
  'LOSS': [
    'his dignity',
    'all his documents',
    'all his money',
    'his hand',
    'his Costco card',
    'his fishing license',
  ],
  'BLEW_UP': ['blew up', 'set on fire', 'tipped over'],
  'KILL': ['scare', 'prank'],
  'RETURN_M': ['his wife', 'his girlfriend', 'the family honor'],
  'RETURN_F': ['her husband', 'her teenager from camp', 'the family honor'],
  'ACCIDENTALLY': ['accidentally', '', '', '', ''],
  'TWO': ['Two', 'Three'],
  'OFFICIAL': ['the mayor', 'the governor', 'city hall', 'the senator'],
  'MOONSHINE': ['moonshine', 'whiskey', 'kombucha', 'hot sauce', 'pickle brine'],
  'OLDMANS': [
    'retirees',
    'veterans',
    'hunters',
    'gardeners',
    'bowlers',
    'fishermen',
    'book club members',
    'neighbors',
  ],
};

Map<String, List> globalAction = {
  'm': [
    '[ВЗОРВАЛ] [БУДКУ]',
    'боролся с неприятным запахом в туалете',
    'взял в заложницы тещу',
    'вломился в чужой дом',
    'выстрелил в сожительницу из ружья',
    'выстрелил мужчине в глаз',
    'готовил ужин',
    'залез в дом пенсионерки',
    'в порыве страсти зарезал собутыльницу',
    'заготовил на зиму 3 кг марихуаны',
    'записался на шугаринг',
    'захватил сосны на участке соседей',
    'зашел в строительную фирму',
    'избил несовершеннолетнего',
    'изнасиловал кондуктора',
    'изнасиловал коллектора',
    'купил аккордеон',
    'напал на офис микрозаймов',
    'напоил кота самогонкой',
    'нашёл две гранаты',
    'незаконно охотился на косуль',
    'обесточил посёлок',
    'ОБЛИЛСЯ БЕНЗИНОМ, ЗАГОРЕЛСЯ',
    'обнаружил в подвале скелет',
    'ограбил автомат с игрушками',
    'ограбил супругов, приютивших его на ночь',
    'отравился этанолом',
    'ПОДЖЕГ СВОИ ДОКУМЕНТЫ',
    'поджёг не ту аптеку',
    'подорвался на корпоративе',
    'позарился на самокат соседа',
    'попался на краже велосипеда',
    'поссорился с бабушкой',
    'пошёл на рыбалку',
    'провёл ночь в гнезде аиста',
    'провёл ночь в муравейнике',
    'прочитал лекцию о сексуальной ориентации',
    'пытался провезти [СВОЕГО_ЛЮБИМЦА] в чемодане',
    'РАЗВЕЛ КОСТЕР В МЕТРО',
    'раздал свою зарплату бомжам',
    'ранил ножом двоих полицейских',
    'напал на прохожего с огнетушителем в руках',
    'сбежал из кареты скорой помощи',
    'сбежал из психушки',
    'собирал валежник',
    'убирался в квартире',
    'УГНАЛ [МАРШРУТКУ]',
    'УКРАЛ [СОБАКУ]',
    'украл выручку',
    'украл катафалк, увёз его в деревню',
    'утопил знакомую в ванной',
    'хвастался в Instagram брендовыми вещами',
    'ХОТЕЛ [УБИТЬ] [ЖЕНУ]',
    'хотел устроиться на работу в детский сад',
  ],
  'f': [
    '[ВЗОРВАЛА] [БУДКУ]',
    'брала взятки',
    'взяла в заложники тестя',
    'вломилась в чужой дом',
    'готовила ужин',
    'забрала ёлку в отделении банка',
    'заколола мужа во время застолья',
    'избила новогодней ёлкой директора школы',
    'избила детей скакалкой',
    'не пустила мужа на рыбалку',
    'ОБЛИЛась БЕНЗИНОМ, ЗАГОРЕЛась',
    'ограбила автомат с игрушками',
    'отдала зарплату аферисту',
    'ПОДожгла СВОИ ДОКУМЕНТЫ',
    'пыталась украсть продукты в подгузнике',
    'РАЗВЕЛа КОСТЕР В МЕТРО',
    'раздала зарплату детям-сиротам',
    'сбежала из психушки',
    'сломала самогонный аппарат мужа',
    'снялась обнажённой',
    'снялась в порно',
    'совершила ДТП с трактором',
    'убила сестру банкой муки',
    'УГНАЛА [МАРШРУТКУ]',
    'УКРАЛА [СОБАКУ]',
    'поймала [СОБАКУ]',
    'гонялась за соседским ребёнком',
    'фотографировала льва в цирке',
    'ХОТЕЛа [УБИТЬ] [МУЖА]',
  ],
  'plural': [
    'взорвали [БУДКУ]',
    'вломились в чужой дом',
    'выманили у студентки 2 млн рублей',
    'задержали подростка с автоматом Калашникова',
    'заказали убийство директора',
    'избили на концерте полицейского',
    'изнасиловали кондитера',
    'ограбили автомат с игрушками',
    'осквернили могилу неизвестного солдата',
    'подожгли гаражный кооператив',
    'ПОДожгли СВОИ ДОКУМЕНТЫ',
    'подрались из-за трусов в секонд-хенде',
    'пошли на рыбалку',
    'провезли в метро гроб',
    'пытались покончить с собой',
    'РАЗВЕЛи КОСТЕР В МЕТРО',
    'раздали свою зарплату бомжам',
    'сбежали из психушки',
    'сломали самогонный аппарат',
    'угнали бетономешалку',
    'УГНАЛИ МАРШРУТКУ, НАБРАЛИ ПАССАЖИРОВ',
    'угнали танк-экспонат времен ВОВ',
    'угнали трактор',
    'угнали у фермера стадо баранов',
    'УКРАЛИ [СОБАКУ]',
    'УКРАЛИ чемодан, набитый дошираком',
    'украли ларёк "Твоя любимая шаверма"',
    'украли льва из местного цирка',
    'украли несколько тонн сигарет',
    'украли у горожан 20 млн рублей',
    'устроили поножовщину с Дедом Морозом',
  ]
};

Map<String, List> globalActionEn = {
  'm': [
    '[BLEW_UP] [GARAGE]',
    'fought a bad smell in the bathroom',
    'took his mother-in-law hostage',
    'broke into someone else\'s house',
    'shot a man in the eye with a BB gun',
    'was cooking dinner',
    'broke into a retiree\'s house',
    'killed a drinking buddy in a fit of passion',
    'stockpiled 3 kg of oregano for winter',
    'signed up for a waxing appointment',
    'stole pine trees from the neighbor\'s yard',
    'walked into a construction company office',
    'beat up a teenager',
    'bought an accordion',
    'fed the cat [MOONSHINE]',
    'DRENCHED HIMSELF IN GASOLINE AND CAUGHT FIRE',
    'found a skeleton in the basement',
    'robbed a claw machine',
    'robbed the couple who let him stay the night',
    'got food poisoning from gas station sushi',
    'BURNED HIS DOCUMENTS',
    'set the wrong pharmacy on fire',
    'blew himself up at the office party',
    'tried to steal a neighbor\'s e-scooter',
    'got caught stealing a bicycle',
    'had a fight with his grandmother',
    'went fishing',
    'spent the night in a stork\'s nest',
    'spent the night in an anthill',
    'gave a lecture on backyard composting',
    'tried to smuggle [PET] in a suitcase',
    'STARTED A BONFIRE IN THE SUBWAY',
    'handed out his paycheck to homeless people',
    'wounded two police officers with a spatula',
    'attacked a passerby with a fire extinguisher',
    'escaped from an ambulance',
    'escaped from a psychiatric hospital',
    'was collecting fallen branches in a national park',
    'was cleaning the apartment',
    'STOLE [TRAIN]',
    'STOLE [PET]',
    'stole the day\'s cash register takings',
    'stole a hearse and drove it to a village',
    'drowned an acquaintance in the bathtub',
    'bragged on Instagram about designer clothes',
    'TRIED TO [KILL] [WIFE]',
    'tried to get a job at a daycare',
    'declared himself king of the cul-de-sac',
    'live-streamed himself mowing the lawn at 3 a.m.',
  ],
  'f': [
    '[BLEW_UP] [GARAGE]',
    'took bribes',
    'took her father-in-law hostage',
    'broke into someone else\'s house',
    'was cooking dinner',
    'stole a Christmas tree from a bank lobby',
    'stabbed [HUSBAND] during Thanksgiving dinner',
    'hit the school principal with a folding chair',
    'chased children with a jump rope',
    'did not let [HUSBAND] go fishing',
    'DRENCHED HERSELF IN GASOLINE AND CAUGHT FIRE',
    'robbed a claw machine',
    'gave her paycheck to a phone scammer',
    'BURNED HER DOCUMENTS',
    'tried to shoplift groceries in a diaper box',
    'STARTED A BONFIRE IN THE SUBWAY',
    'donated her salary to an orphanage',
    'escaped from a psychiatric hospital',
    'smashed her husband\'s home brewery',
    'caused a pileup with a riding mower',
    '[KILLED] her sister with a bag of flour',
    'STOLE [TRAIN]',
    'STOLE [PET]',
    'caught [PET]',
    'chased a neighbor\'s kid down the block',
    'photographed a lion at the county fair',
    'TRIED TO [KILL] [HUSBAND]',
    'sold homemade candles on the highway median',
  ],
  'plural': [
    '[BLEW_UP] [GARAGE]',
    'broke into someone else\'s house',
    'scammed a student out of \$2 million',
    'detained a teenager with a water pistol',
    'ordered a hit on their boss',
    'started a brawl at a county fair',
    'robbed a claw machine',
    'desecrated the grave of an unknown soldier',
    'set a storage unit complex on fire',
    'BURNED THEIR DOCUMENTS',
    'fought over thrift-store jeans',
    'went fishing',
    'took a coffin on the subway',
    'tried to commit suicide',
    'STARTED A BONFIRE IN THE SUBWAY',
    'handed out their paychecks to homeless people',
    'escaped from a psychiatric hospital',
    'smashed a home brewery',
    'stole a concrete mixer',
    'STOLE [TRAIN] AND PICKED UP PASSENGERS',
    'hijacked a WW2 tank from a museum',
    'hijacked a tractor',
    'stole a herd of goats from a farmer',
    'STOLE [PET]',
    'stole a suitcase full of instant noodles',
    'robbed a taco truck called "Your Favorite Burrito"',
    'stole a lion from the county fair',
    'stole several tons of cigarettes',
    'stole \$20 million from townspeople',
    'got into a sword fight with a mall Santa',
  ],
};

Map<String, List> globalConclusion = {
  'm': [
    'в неадекватном состоянии',
    'и [СЛУЧАЙНО] оскорбил [ПЕНСИОНЕРОВ]',
    'и [СЛУЧАЙНО] [УБИЛ] [СОСЕДА]',
    'и был задержан за мошенничество',
    'и уволился',
    'и выиграл в лотерею',
    'И ЕДВА НЕ ЛИШИЛСЯ [ЛИШИЛСЯ]',
    'и пел матерные частушки',
    'и поджег квартиру',
    'и получил пулю в живот',
    'и просил встречи с [ПУТИНЫМ]',
    'и угнал шесть автомобилей',
    'и украл кошелек с деньгами',
    'и уехал выпивать в деревню',
    'и уехал на товарняке во Владивосток',
    'И УМЕР',
    'и умер от удара током',
    'и устроил пенную вечеринку',
    'и чуть не убил [СВОЕГО_ЛЮБИМЦА]',
    'спасая [СВОЕГО_ЛЮБИМЦА]',
    'чтобы вернуть [ВЕРНУТЬ_М]',
    'чтобы войти в книгу рекордов Гинесса',
    'чтобы его оставили в покое',
    'чтобы замести следы изготовления самогона',
    'чтобы защитить свою честь',
    'чтобы отомстить',
    'ЧТОБЫ СОГРЕТЬСЯ',
    'чтобы уладить конфликт с соседом',
  ],
  'f': [
    'и [СЛУЧАЙНО] [УБИЛА] [СОСЕДА]',
    'и оскорбила [ПЕНСИОНЕРОВ]',
    'и выиграла в лотерею',
    'и выложила фото в инстраграмм',
    'и едва не лишилась [ЛИШИЛСЯ]',
    'и живёт одна уже несколько месяцев',
    'и материлась невпопад',
    'и НАДРУГАЛАСЬ над соседом',
    'И ПОПРОСИЛа НЕ БЕСПОКОИТЬ',
    'И ПРИ ЭТОМ СМЕЯЛась',
    'и скрывается от правосудия',
    'и требовала аудиенции с [ПУТИНЫМ]',
    'И УМЕРла',
    'ради веселья',
    'с особой жестокостью',
    'спасая [СВОЕГО_ЛЮБИМЦА]',
    'чтобы вернуть [ВЕРНУТЬ_Ж]',
    'чтобы вернуть мужа',
    'чтобы войти в книгу рекордов Гинесса',
    'чтобы её не заподозрили в измене',
    'чтобы её оставили в покое',
    'чтобы уладить конфликт с соседкой',
    'ЧТОБЫ СОГРЕТЬСЯ',
  ],
  'plural': [
    'в знак протеста против произвола христиан',
    'и [СЛУЧАЙНО] [УБИЛИ] [СОСЕДА]',
    'и оскорбили [ПЕНСИОНЕРОВ]',
    'И ЕДВА НЕ ЛИШИЛись конечностей',
    'и пели матерные частушки',
    'И ПОПРОСИЛи НЕ БЕСПОКОИТЬ',
    'И ПРИ ЭТОМ СМЕЯЛись',
    'и отправились гулять по железнодорожным путям',
    'и прострелили ногу преступнику с ножом',
    'и скрываются от правосудия',
    'и добивались встречи с [ПУТИНЫМ]',
    'И УМЕРли',
    'и устроили стрельбу из пневматики',
    'ради веселья',
    'с особой жестокостью',
    'с целью друг друга убить',
    'спасая [СВОЕГО_ЛЮБИМЦА]',
    'угрожая оружием',
    'чтобы войти в книгу рекордов Гинесса',
    'чтобы их оставили в покое',
    'чтобы наладить дружеские отношения',
    'чтобы уладить конфликт с соседями',
    'ЧТОБЫ СОГРЕТЬСЯ',
  ]
};

Map<String, List> globalConclusionEn = {
  'm': [
    'while clearly not in his right mind',
    'and [ACCIDENTALLY] offended [OLDMANS]',
    'and [ACCIDENTALLY] [KILLED] [NEIGHBOR]',
    'and was detained for fraud',
    'and quit his job on the spot',
    'and won the lottery',
    'and nearly LOST [LOSS]',
    'and sang dirty sea shanties',
    'and set fire to the apartment',
    'and took a paintball to the leg',
    'and demanded a meeting with [OFFICIAL]',
    'and stole six cars in one night',
    'and stole a wallet full of coupons',
    'and drove to a village to keep drinking',
    'and hopped a freight train to Seattle',
    'AND DIED',
    'and died of electric shock',
    'and threw a foam party',
    'and nearly harmed [PET]',
    'while saving [PET]',
    'to win back [RETURN_M]',
    'to enter the Guinness Book of Records',
    'to be left alone',
    'to hide evidence of brewing [MOONSHINE]',
    'to defend the family honor',
    'to get revenge',
    'TO STAY WARM',
    'to settle a dispute with a neighbor',
  ],
  'f': [
    'and [ACCIDENTALLY] [KILLED] [NEIGHBOR]',
    'and [ACCIDENTALLY] offended [OLDMANS]',
    'and won the lottery',
    'and posted it on Instagram',
    'and nearly LOST [LOSS]',
    'and has lived alone for months',
    'and swore at the wrong people',
    'and pranked a neighbor',
    'and ASKED TO BE LEFT ALONE',
    'AND LAUGHED THE WHOLE TIME',
    'and is hiding from the police',
    'and demanded a meeting with [OFFICIAL]',
    'AND DIED',
    'just for fun',
    'while saving [PET]',
    'to win back [RETURN_F]',
    'to win her husband back',
    'to enter the Guinness Book of Records',
    'so nobody would suspect an affair',
    'to be left alone',
    'to settle a dispute with a neighbor',
    'TO STAY WARM',
  ],
  'plural': [
    'in protest against daylight saving time',
    'and [ACCIDENTALLY] [KILLED] [NEIGHBOR]',
    'and [ACCIDENTALLY] offended [OLDMANS]',
    'and nearly lost their limbs',
    'and sang dirty sea shanties',
    'and ASKED TO BE LEFT ALONE',
    'AND LAUGHED THE WHOLE TIME',
    'and went for a walk on the railroad tracks',
    'and shot a knife-wielding robber in the leg',
    'and are hiding from the police',
    'and demanded a meeting with [OFFICIAL]',
    'AND DIED',
    'and staged a BB-gun shootout',
    'just for fun',
    'while trying to prank each other',
    'while saving [PET]',
    'while waving garden tools',
    'to enter the Guinness Book of Records',
    'to be left alone',
    'to become friends again',
    'to settle a dispute with neighbors',
    'TO STAY WARM',
  ],
};

List<String> russianLocales = [
  'ru',
  'be',
  'uk',
];
